language: go

go:
    - 1.6
    - tip

sudo: false

before_install:
    # Install tools necessary to report code-coverage to Coveralls.io
    - go get github.com/mattn/goveralls

install:
    # Get all imported packages
    - make install-deps install-deps-dev

    # Basic build errors
    - make build

script:
    # Lint
    - make format-lint
    - make import-lint
    - make copyright-lint

    # Run tests
    - make test

after_success:
    # Report our code-coverage to Coveralls.io
    - goveralls -service=travis-ci

matrix:
    allow_failures:
        - go: tip
    fast_finish: true
